name: Build and Deploy Webapp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_deploy:

    # runner
    runs-on: ubuntu-latest

    steps:

      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Java JDK 11
      - name: set JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      # Set up sha_short variable
      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Build
      - name: Build Artifact
        run: |
          cd webappone
          mvn clean install

      # Install Packages
      - name: Install apt & zip
        run: sudo apt-get update && sudo apt-get install wget zip unzip -y

      # AWS CLI pre-installed in Ubuntu-Latest

      # AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # Zip Artifact
      - name: Zip Artifact
        run: |
          mkdir codedeploy_artifact
          zip -r webapp-${{ steps.vars.outputs.sha_short }}.zip \
          ./webappone/target/webappone-0.0.1-SNAPSHOT.jar ./codedeploy/*.sh appspec.yml
          mv webapp-${{ steps.vars.outputs.sha_short }}.zip ./codedeploy_artifact

      # Upload Artifacts to S3
      - name: Upload Artifacts
        run: |
          aws s3 sync ./codedeploy_artifact s3://${{ secrets.S3_BUCKET_NAME }}


      # Deploy Artifact to EC2
      - name: Deploy Webapp
        run: |
          output=$(aws deploy create-deployment \
          --application-name "csye6225-webapp" \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name "csye6225-webapp-deployment" \
          --description "deploy webapp" \
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},bundleType=zip,key=webapp-${{ steps.vars.outputs.sha_short }}.zip \
          --region us-east-1 \
          --output json)

          echo $output

          dId=$(echo $output | jq -r '.deploymentId')

          aws deploy wait deployment-successful --deployment-id $dId
